### ISSUE TITLE
Future development of Maputnik

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#121]
Hi,

first of all, I want to say thank you very much to Lukas Martinelli and everybody else contributing to this amazing project!

As stated in the initial [kickstarter campaign](https://www.kickstarter.com/projects/174808720/maputnik-visual-map-editor-for-mapbox-gl?lang=en) :

> The main goal is to create a free alternative to the cloud based Mapbox Studio and allow businesses and individuals to create their maps without tying themselves to services of a single company but still profit from the amazing Mapbox GL ecosystem.

I heard about that [Lukas Martinelli is working now for Mapbox](https://www.mapbox.com/about/team/lukas-martinelli/). 

Congratulations to the new job! But this leads to the question if this situation means something for the future development of Maputnik as the main goal of this project and the interests of Mapbox might be in conflict.

Some feedback would be nice to have an idea in which direction this project goes in the future.

Thanks again for creating this very useful editor.

**Comment by jingsam** [comment]
I have the same concern.  Maybe transfer this repo to someone else

**Comment by lukasmartinelli** [comment]
> Mapbox has built one of the best and most amazing OSS ecosystems. A key component to ensure its longevity and independence is an OSS map designer.

I really prefer the mission statement in the GitHub repo.

> Congratulations to the new job! But this leads to the question if this situation means something for the future development of Maputnik as the main goal of this project and the interests of Mapbox might be in conflict. 

Apart from that it is simply a matter of lack time of maintaining this project without external help.

> I have the same concern. Maybe transfer this repo to someone else

All the projects live under the https://github.com/maputnik/ organization not my personal account for a reason - I explicitly encourage other people to maintain this project and @orangemug and @muesliq have done a good start doing this.

I still hope that organizations who use this project will commit back and commit resources to it (which I tried to organize in https://github.com/maputnik/editor/issues/69).

It is hard to plan OSS maintainership of projects because you entirely need to rely that someone else feels very passionate about a project - I would love if this project would draw more outside contributors (like OSM2VT did) and get a new maintainer (that also should get all the credit for this work).

## Roadmap

- **Maputnik is in a stable and absolutely usable state** which I am very proud of and invested 8 weeks of full time work (all of that with the tiny budget of the Kickstarter campaign) and.
- Thanks to the JSON mode it will keep up  with the style spec (which moves fast - even for Studio it is difficult to keep up). **This guarantees future compatibility.**
- **New features** such as data driven styling are **very hard to do** (at min. 1-2 weeks full time) for which I don't have the capacity to do and rely on external contributors to do so
- I will try to coordinate and assist in bugfixes for the project
- **I am looking for new maintainers** to take over and push this project further/ present at conferences or whatever they think is right for it.

**Comment by ulimueller** [comment]
Hi Lukas

Thank you a lot for your phantastic work on Maputnik up to now and also for the estimation, you made above about the future of the project. I understand that you won't be able to invest much time for Maputnik, and that the project should become autonomous from your personal engagement. However I am still curious how you judge the future legal situation. Can we be confident that MapBox will not claim intellectual property of any of the components Maputnik relies on (starting with MapBox GL JS specification, the tile rendering components or the GUI concept of Maputnik or anything else)? So, can you - also under a legal aspect and according to your current more intimate knowledge of MapBox policies - encourage individuals and companies to invest time and money into the future development and usage of Maputnik?

Uli

**Comment by muesliq** [comment]
Hi @ulimueller, 

Mapbox has a great track record when it comes to open source, both with software from staff they hired (eg. LeafletJS or OSRM) and with software they themselves opensourced. Also they cannot legally un-opensource the Mapbox GL specification as it is under a BSD licence. There's no way back from that. The only possible impediment that I could imagine is to forbid @lukasmartinelli to contribute further. Lukas has already started at Mapbox and still contributes, so it appears they do not mind too much. 

In my opinion no one can keep people from using and advancing Maputnik, neither Mapbox nor  Lukas (as Maputnik is under a MIT licence and could easily be forked).

**Comment by muesliq** [comment]
I guess the concerns have been addressed sufficiently? Closing this for now.
