### ISSUE TITLE
Unable to remove active source

### ISSUE THREAD

**Issue by ericsvendsen** [maputnik/editor#206]
I'm trying to figure out how to remove all active sources in the editor. For example, if you go to https://maputnik.github.io/editor, click the "Sources" menu, and try to remove `#openmaptiles` from active sources, it doesn't work and an error occurs:
```
layers[1]: source "openmaptiles" not found
layers[37]: source "openmaptiles" not found
```
How can I remove the default active source?

**Comment by orangemug** [comment]
That'll probably be because it's currently used in your active style. If you click 'open' you can start with an empty style.

Does that help?

**Comment by ericsvendsen** [comment]
Yes, I see that now. Sorry, that should have been obvious to me. Now once I figure out how to default to an empty style I'll be all set. Thanks!

**Comment by orangemug** [comment]
If you click "Open" from the toolbar there is an "Empty style" in the "Gallery Styles" section.

**Comment by ericsvendsen** [comment]
Right, sorry that's not what I meant. I'm building this project from source to use on a closed network, and I'd like the app start out with an empty style and, by extension, no default source.

**Comment by orangemug** [comment]
Ah ok sorry I misunderstood. There is a `?style=` parameter for loading a style from the url if that helps.

Example <https://maputnik.github.io/editor/?style=https://raw.githubusercontent.com/lukasmartinelli/osm-liberty/gh-pages/style.json#3.81/50.40/20.75> replace with whatever style you'd like to load

Anyway it looks like your problem is solved, so I'll close the issue.
