### ISSUE TITLE
Adding GeoJSON files example video

### ISSUE THREAD

**Issue by chebourne** [maputnik/editor#210]
I don't know what i'm doing wrong - following the video: https://www.youtube.com/watch?v=hzJ-CPVykDE

for adding external GeoJSON files and I get nothing. 

I have tried online Maputnik and Local - running on windows. Have tried Firefox and Chrome.

I choose blank style at opening and follow the video copying links from geojson.xyz and adding as sources but I get nothing when going to inspect mode.

Any idea what I have missed?

**Comment by pathmapper** [comment]
Just tried it using online Maputnik with "Populated Places" https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_populated_places.geojson and it works for me:

![image](https://user-images.githubusercontent.com/20856381/33804638-4229f4d4-dda9-11e7-976f-7e23befa5157.png)



Do you switch the "Source Type" to "GeoJSON" when adding the new source?

![image](https://user-images.githubusercontent.com/20856381/33804631-3003b466-dda9-11e7-849c-f60f75ca3841.png)

**Comment by chebourne** [comment]
Yes, I am choosing GeoJSON - still no luck for me.

![image](https://user-images.githubusercontent.com/20801744/33825446-8d8b4968-de59-11e7-8c5c-f22c3d800a67.png)


Have tried:
Firefox 58.0b10 (64bit) on Windows 7
Chrome 63.0.3239.84 (64bit) on Windows 7
Firefox 57.0.1 (64bit) on Windows 10
Chrome 62.0.3202.94 (64bit) on Windows 10

Maputnik works without any problems otherwise.

Is there anyway of checking as F12 debugger doesn't bring much up?

Addendum - I can sometimes get it working with Chrome on Win7 but it is intermittent and I can't pin down replicating it. Firefox does not seem to work at all. Has nobody had similar problems?

**Comment by orangemug** [comment]
Hey @chebourne so basically there are two things that are most likely incorrect. Either the editor hasn't added the source correctly to the style or mapbox-gl-js can't request the source

To help us further diagnose the issue.

 1. Export the network trace
    1. In chrome open the inspector go to the network tab.
    2. Refresh the page and complete the action
       - Add the geojson source
       - Switch to inspect mode
    3. Right click on network tab "Save as HAR with content"
    4. Attach file to comment in this ticket 
 2. Export the style and attach file to comment in this ticket

**Comment by pathmapper** [comment]
@chebourne noticed on your screenshot that you are using http://editor.openmaptiles.org .
Did you try it also with https://maputnik.github.io/editor/? Looks like there are differences between both versions, e.g. https://github.com/maputnik/editor/pull/133 is available with editor.openmaptiles.org . Also maputnik.github.io/editor/ is using SSL by default.

Tried it again with both versions and now having also most of the times the issue described (sometimes it works).

@orangemug could it be that this is related to access to local storage?
Please have a look at the console outputs, http://localhost:3000/geojson.json is not loaded. For maputnik.github.io it fails because of mixed content.
[styles_and_network_traces.zip](https://github.com/maputnik/editor/files/1547922/styles_and_network_traces.zip)


maputnik.github.io/editor

![image](https://user-images.githubusercontent.com/20856381/33831118-0d6800f0-de77-11e7-9594-458785746ef1.png)

editor.openmaptiles.org

![image](https://user-images.githubusercontent.com/20856381/33832155-30c6cc12-de7b-11e7-91bb-efec6ef7f25e.png)

**Comment by orangemug** [comment]
@pathmapper browsers won't allow requests from `http -> https` or `https -> http`. If you use https://editor.openmaptiles.org you'll get the same error.

**Comment by pathmapper** [comment]
@ hmm, I thought `http -> https` is possible.

Here is an example where it was possible to add the geojson source:

editor.openmaptiles.org (`http`) was able to get the geojson file via `https`

![image](https://user-images.githubusercontent.com/20856381/33834531-86f5cff4-de83-11e7-9547-be7276435300.png)

**Comment by chebourne** [comment]
Thanks for looking into this but I assume there is no conclusion. I tried from https instead but still no luck.

HAR and style files attached as requested by @orangemug 
[maputnik.zip](https://github.com/maputnik/editor/files/1549267/maputnik.zip)

**Comment by chebourne** [comment]
Just got back to trying this again and still no luck. I even downloaded the example geojson files from geojson.xyz. stored them on a local web server (on port 80), ran Maputnik locally (on port 8000), added the geojson sources from the local server e.g. http://localhost/GeoJSON/ne_50m_ocean.geojson. So nothing on https all on http and still no luck - nothing showing when entering inspect mode - geojson files appear to load ok:
![image](https://user-images.githubusercontent.com/20801744/34940539-ca8257a4-f9e7-11e7-8dc5-792d6e2a324b.png)
Style file resulting from this is attached as well - seems to be ok?
[1ng3z2vmw.zip](https://github.com/maputnik/editor/files/1631475/1ng3z2vmw.zip)
It seems people have replicated this problem - can anyone else take a look?

**Comment by orangemug** [comment]
@chebourne was this solved with your solution in #215, and if so can we close this issue?

**Comment by KarolDaniluk** [comment]
@orangemug I have exactly the same problem right now.
