### ISSUE TITLE
Export to preview in Gist blocks.org Mapbox basemaps not displaying

### ISSUE THREAD

**Issue by pkgeo** [maputnik/editor#230]
Hello, 
I'm using v 1.1.0, trying to export to view in Gist and using any of mapbox basemap (satellite, basic, bright) won't display their basemap. Using klokantech basemap displays fine. Here is gist
https://bl.ocks.org/anonymous/1e97f8d9cf35cdff8f9181ddd39abf76

Here is mapbox basic basemap: https://bl.ocks.org/anonymous/e708c1684163404fbdd5d308e6e7f686
I downloaded index and style locally to display but it stills shows no basemap. 

Here is my maputnik editor export link (this is fantastic feature, btw)
I'm using king county open data portal geojson data,  https://maputnik.github.io/editor/?style=https://gist.githubusercontent.com/anonymous/f07f974a19b880f9786d21b0493f1385/raw/add064b9009967bf47cc6f4be57fb97bb56098c2/style.json

I love export feature to view through blocks.org and not sure why mapbox basemaps are not displaying.

**Comment by pathmapper** [comment]
Hi @pkgeo ,
the Mapbox basemap is not displayed because of a missing Mapbox access token.

As far as I can see, there is currently no option to provide a Mapbox access token when saving a style to a gist including a preview.

![image](https://user-images.githubusercontent.com/20856381/35611801-8c9437f6-0666-11e8-86b1-216be4c1a5f6.png)

To workaround, you may manually add your acces token to the `index.html` of your Gist like this:
`mapboxgl.accessToken = 'YourAccessToken';`

![image](https://user-images.githubusercontent.com/20856381/35611415-3127ae26-0665-11e8-9df6-9bf117c16786.png)

**Comment by keum** [comment]
Thanks @pathmapper! I'll use this method. I think you can close this ticket.

**Comment by orangemug** [comment]
Actually leave this open and we'll fix it properly. It should present an `<input />` where you can enter your mapbox token.

**Comment by keum** [comment]
That'll be awesome to input your own mapbox token or klokantech token to get your basemap display!

**Comment by pathmapper** [comment]
In the _Style Settings_ there is already a field to put a Mapbox token:


![image](https://user-images.githubusercontent.com/20856381/35644148-7e6cb27c-06c8-11e8-952a-afad26776bc4.png)

If there is a Mapbox token available in the _Style Settings_, it would be good to pass it through to the _Export Style_ settings (to the new field which will be created), like it is working currently with the OpenMapTiles token.

By the way:
@orangemug do you know if it's still OK to use the [fallback Mapbox token](https://github.com/maputnik/editor/blob/master/src/config/tokens.json#L2), see also https://github.com/maputnik/editor/issues/80 .
I wonder if it's coming from a [Pay-As-You-Go](https://www.mapbox.com/pricing/) plan and who cares for it.

Regarding the OpenMapTiles fallback token I assume it is OK, because @klokan is involved here.

**Comment by orangemug** [comment]
@pathmapper thats a good question, I don't know I'm afraid @lukasmartinelli can you confirm the status of those tokens? (see https://github.com/maputnik/editor/blame/master/src/config/tokens.json#L2)

**Comment by orangemug** [comment]
> In the Style Settings there is already a field to put a Mapbox token

@pathmapper yeah you're right we should just use the tokens already present. How about if they exist we include them in the export otherwise just include a commented out line where a user can add them. Similar to your example in https://github.com/maputnik/editor/issues/230#issuecomment-361856940

```
// mapboxgl.accessToken = 'YourAccessToken';
```

**Comment by pathmapper** [comment]
> How about if they exist we include them in the export

@orangemug I'm all for it!

I think an OpenMapTiles token is already included in the _Export_ if present in _Style Settings_ .

> otherwise just include a commented out line where a user can add them. 

I think I wouldn't do it for three reasons:
1. The commented out line won't work for an OpenMapTiles token, because it is added like this to a TileJSON URL: `https://free.tilehosting.com/data/v3.json?key=YourKey` into the `style.json`.

2. A user would have two options in Maputnik, where he can enter one of these two access tokens: 
_Style Settings_ and _Export Style_ (should be enough and we could also document it in the Wiki).

3. For self hosted tiles there is no need to provide one of these two tokens (and I would assume in most cases no token at all).

It would be great if an export including a preview on bl.ocks.org would be possible for self hosted tiles (currently in this case there is "only" an export of the `style.json ` to Gist possible as far as I can see).

**Comment by orangemug** [comment]
> currently in this case there is "only" an export of the style.json to Gist possible as far as I can see

The preview works you just need to provide a openmaptiles token currently and tick the 'preview' button (its a bug)

> The commented out line won't work for an OpenMapTiles token

Yeah my apologies, I meant just for the mapbox token. Although I realised you can just leave it blank rather than commented out.

All that said here is a PR for these issues #235 and you can see a demo here <https://207-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.bMlA3xn/build/index.html>. Give it a test @pathmapper @keum see what you think.

**Comment by keum** [comment]
@orangemug i just tried out your demo from link above...it works nicely w/ my public access tokens and with klokantech too! pretty sweet... https://bl.ocks.org/anonymous/7c930434648bfb2117e460876ca7aa5d
this is mapbox basic style w/ county open data geojson zipcode data.

**Comment by pathmapper** [comment]
Tested the export including preview with styles using:
- tiles hosted by OpenMapTiles (https://free.tilehosting.com) / own OpenMapTiles key
- tiles hosted by Mapbox / own Mapbox access token
- self hosted tiles / no key or token

All these are working great, also if the key/token is put in _Style Settings_.  Thanks @orangemug !

The only thing I've noticed:
When exporting a style including preview using tiles hosted by OpenMapTiles (https://free.tilehosting.com) without providing an own key, the [fallback key](https://github.com/maputnik/editor/blame/master/src/config/tokens.json#L3) is exported. In this case the export should be `key={key}`.

**Comment by klokan** [comment]
Could you please ensure the fallback key is never used for exports and is never visible to the user of maputnik in the interface or saved JSON files?

The key is a personal thing, people should get their own. If it is used outside of https://maputnik.github.io/editor/ we will need to block it and provide you with a different one.

**Comment by pathmapper** [comment]
> Could you please ensure the fallback key is never used for exports and is never visible to the user of maputnik in the interface or saved JSON files?

As far as I can see it is working like as you described in the current release: https://maputnik.github.io/editor/

What I've mentioned in https://github.com/maputnik/editor/issues/230#issuecomment-362503328 is a bug related to https://github.com/maputnik/editor/pull/235 .

**Comment by orangemug** [comment]
> Could you please ensure the fallback key is never used for exports and is never visible to the user of maputnik

@klokan that's the current situation, and I'll do my best to make sure it stays that way.

**Comment by pathmapper** [comment]
@orangemug sorry if I misunderstood something or wasn't clear, but for me it looks like you've just merged https://github.com/maputnik/editor/pull/235 without modification and the OpenMapTiles fallback key is exported using the demo you've provided (only when _include preview_ is checked): https://207-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.bMlA3xn/build/index.html#12.24/47.37181/8.54807

**Comment by orangemug** [comment]
Ah you're correct @pathmapper that's also the case in the live version. I'll look at that today, look like it's been that way for a while.

Sorry for the confusion, @pathmapper I think the PR is still ok. I think the issue lies elsewhere. Sorry @klokan this is my priority for later on today.

**Comment by pathmapper** [comment]
Thanks @orangemug , some more thoughts which might be helpful:

I don't see this issue in the live version. When there is no OpenMapTiles key provided and _Include preview_ is checked, after _Save to Gist (anonymous)_ there is only a link _Source_ (and no link _Preview_ ):

![image](https://user-images.githubusercontent.com/20856381/35734541-d27f0ef0-0821-11e8-8e2e-a1717c2ea051.png)






The gist behind the _Source_ link looks like the following, so everything should be OK with the live version:


![image](https://user-images.githubusercontent.com/20856381/35734765-8cdd235e-0822-11e8-8271-da0b8f23d9b5.png)

**Comment by klokan** [comment]
Thank you guys for verifying this...

BTW It would be clever for the interface to display only the relevant input box for a key.
Hardly ever you would need to fill both Mapbox and OpenMapTiles keys.
There is no point to ask the user for a Mapbox key if he has no source / fonts / glyphs requiring the key in his style.

I am glad people enjoy the Gist export with the Preview which @jirik from @klokantech team developed and contributed to Maputnik. It is great to see people are using it...

BTW Thanks for v1.1 release - amazing effort!

**Comment by orangemug** [comment]
@pathmapper yeah you're 100% correct, I misunderstood the issue. I believe PR #240 fixes exposed keys, see build <https://210-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.UfmqsHf/build/index.html>

> BTW It would be clever for the interface to display only the relevant input box for a key.
Hardly ever you would need to fill both Mapbox and OpenMapTiles keys.
There is no point to ask the user for a Mapbox key if he has no source / fonts / glyphs requiring the key in his style.

Yeah good point @klokan, lets work on that next. I also have a couple of questions regarding https://www.tilehosting.com what's the best way to get in contact?

**Comment by klokan** [comment]
Thanks @orangemug ! Just drop me an email to petr.pridal@klokantech.com

**Comment by orangemug** [comment]
@klokan what's your email address? FYI I followed you on twitter incase you want to DM me instead, I've always been wary of email addresses in issue comments because of spam

**Comment by pathmapper** [comment]
>  I believe PR #240 fixes exposed keys

Looks good! Thank you very much @orangemug !

The following behaviour is the same with the live version and also the #240 demo:
When providing a personal OpenMapTiles key in _Style Settings_ and you export to Gist **without** preview, this personal key is **not** included in the export. 
I don't see this as an issue, but we can discuss in https://github.com/maputnik/editor/issues/239 whether it should be included or not.

Please feel free to close here :-)

> I am glad people enjoy the Gist export with the Preview which @jirik from @klokantech team developed and contributed to Maputnik.

Thanks a lot @klokan, it's really useful and an outstanding feature.
