### ISSUE TITLE
New line in labels on polygons with Mapbox client

### ISSUE THREAD

**Issue by srmanc** [maputnik/editor#368]
This is rather a question to this issue from mapbox:

https://github.com/mapbox/mapbox-gl-js/issues/7203

How is it that maputnik renders line breaks along lines and the newest mapbox client does not?

**Comment by orangemug** [comment]
Maputnik is still on `v0.47.0` of `mapbox-gl` (the latest is `v0.48.0`) so that might be the issue. If you share a minimal test case we can take a look.

**Comment by srmanc** [comment]
Here is the JSFiddle of the Mapbox client:
https://jsfiddle.net/srmanc/L6g07fmw/6/

And here is the (correct) render in Maputnik:
https://maputnik.github.io/editor/?style=https://gist.githubusercontent.com/srmanc/9d6e3c06591d93d9d3432ae01dfbcbe4/raw/e4383b7a8403305a5cb683e5390c1e82beb3bcb0/style.json#5.49/44.853/-67.81

If the upper link doesn't work, please go to maputnik.github.io/editor and load the style from here:

Style json (same as in JSFiddle):
https://gist.githubusercontent.com/srmanc/9d6e3c06591d93d9d3432ae01dfbcbe4/raw/e4383b7a8403305a5cb683e5390c1e82beb3bcb0/style.json

Geojson (same as in Style json, if needed):
https://gist.githubusercontent.com/srmanc/2d48dd35780e5995daa83d7a4e00b854/raw/296de1c6f7534eaf8933bcd6858d19128a26d4d8/polygon.geojson

I do not believe it is a version mismatch, I've tried a lot of combinations and none of them worked. I doubt that it is a style export issue, because I've tried to hardcode the style and geojson in JS - it didn't work either.

Any thoughts appreciated.

**Comment by orangemug** [comment]
Ok so this looks like a bug in Maputnik. I have now idea how it's happening at the moment though. The obvious difference is that Maputnik loads the style as an object into the MapboxGL API, I've tried changing your jsfiddle to load from an object rather than a url but same result unfortunately.

Does anybody else have time to help @srmanc ?

**Comment by srmanc** [comment]
So this is a bug in Maputnik which eliminates a bug in Mapbox? :)

Otherwise agree, if hardcoded, it remains the same.

**Comment by orangemug** [comment]
I'm not sure where the bug lies to be honest. My guess would be that somewhere maputnik we're doing something non standard, but I'm not sure where :/. I'm away from computer at the moment but will have another look when I get back.

Edit: One thing we do use that isn't in your jsfiddle is https://github.com/mapbox/mapbox-gl-rtl-text plugin. Might be worth adding that to your jsfiddle see if it makes a difference.

**Comment by srmanc** [comment]
Awesome! That did the trick.

Here is a corrected jsfiddle:
https://jsfiddle.net/0vur8kqa/1/

This however is obviously a bug in Mapbox right?

Thank you very much for your input.

**Comment by orangemug** [comment]
Yeah to me it seems like a bug with mapbox-gl-js. I would raise an issue and ask the question.

**Comment by orangemug** [comment]
Oh also @srmanc if you were thinking of using [mapbox-gl-rtl-text](https://github.com/mapbox/mapbox-gl-rtl-text) plugin be aware that it's reasonably large. 

Gzipped ~58kb, parsed size ~434kb

**Comment by orangemug** [comment]
Closed issue, just comment if there is anything else remaining and we'll reopen.
