### ISSUE TITLE
Source without https doesn’t get warning

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#374]
As one of the survey respondents pointed out, “source without https should get warning”.

As @orangemug pointed out, we can probably use https://www.mapbox.com/mapbox-gl-js/api/#map.event:error here and print any errors that occur when loading resources.

**Comment by pathmapper** [comment]
> we can probably use https://www.mapbox.com/mapbox-gl-js/api/#map.event:error here

This doesn't throw an error if a source without `https:` is used. 

@orangemug it's not clear for me why we would want a warning here, because for most sources supported protocols are `http:`, `https:`, and `mapbox://<mapid>` (e.g. https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-vector-url). What's the motivation?

**Comment by orangemug** [comment]
@pathmapper because we serve maputnik over `https://` at https://maputnik.github.io/editor/ any sources used will also need to `https://` because of the browsers [Same-origin_policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). So what happens at the moment is users try to use a `http://` source it just fails silently, which isn't a great user experience.

**Comment by pathmapper** [comment]
@orangemug ah, all right. There are already mixed content errors printed to the console in FF and Chrome but I guess you want to make it more visible for the user. 

In this case https://www.mapbox.com/mapbox-gl-js/api/#map.event:error might be usable.
