### ISSUE TITLE
Comparison swiper

### ISSUE THREAD

**Issue by stirringhalo** [maputnik/editor#4]
Great effort, glad to see this! Styling by hand was always the pain...

I'd love to see a comparison wiper like http://45.56.99.211/. I used the editor here https://github.com/erikandre/mapbox-gl-style-editor with some tweaks here https://github.com/stirringhalo/mapbox-gl-style-editor to get the side-swipe.

**Comment by lukasmartinelli** [comment]
I have difficulty to imagine where this might fit?

One could compare revisions of style with each other. But I only save the latest version of a style to keep it simple (all currently edited revisions are in memory though for undo/redo) support.

I am probably not going to implement this because the editor has no support for having two styles at the same time and there is also no notion of having different versions of the same style around since there is no "Publish" step or so.

**Comment by muesliq** [comment]
I really like the idea. My style creation workflow often involves comparison with other styles, not necessarily Mapbox GL styles but also raster tile styles.

While such a swiper would be really useful, it would have to be fast. My experience with GL swipers with vector / raster mixes is that they are very laggy. I prefer using different browser windows that I have 'synchronize' by hand to a laggy swiper.
