### ISSUE TITLE
Unable to add new resource from local tile server (in local maputnik)

### ISSUE THREAD

**Issue by karakostis** [maputnik/editor#402]
I am running maputnik in my localserver and I try to add a new source from my local tile server. I add a Vector XYZ url but nothing appears on the map:

`http://localhost:8080/data/KingCo_2000_Census_BlockGroups/{x}/{y}/{z}.pbf`

I also tried adding with this combination:

`http://localhost:8080/data/KingCo_2000_Census_BlockGroups/{z}/{x}/{y}.pbf`

I get no errors on the inspector.

Anyone can advise me how to make it work? I need to add the source to style the layer and get information about the source-layer (is there another way to get information about the source-layer?)

**Comment by pathmapper** [comment]
@karakostis did you check the console and network logs from the browsers inspector? The following thread has some debugging tips: https://github.com/maputnik/editor/issues/208

**Comment by karakostis** [comment]
@pathmapper yes I have checked that thread. I get the following error in my network logs:

`Cannot GET /data/wld_airports.mbtiles/{x}/{y}/{z}.pbf`

and in my console:

`mapbox-gl.js:29 GET http://localhost:8080/data/wld_airports.mbtiles/%7Bz%7D/%7Bx%7D/%7By%7D.pbf 404 (Not Found)
t.getJSON @ mapbox-gl.js:29
k @ mapbox-gl.js:33
i.load @ mapbox-gl.js:33
i.onAdd @ mapbox-gl.js:33
i.onAdd @ mapbox-gl.js:33
i.addSource @ mapbox-gl.js:33
(anonymous) @ mapbox-gl.js:33
i.setState @ mapbox-gl.js:33
o.setStyle @ mapbox-gl.js:33
updateMapFromProps @ MapboxGlMap.jsx:96
componentDidUpdate @ MapboxGlMap.jsx:105
commitLifeCycles @ react-dom.development.js:9792
commitAllLifeCycles @ react-dom.development.js:11455
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:11594
completeRoot @ react-dom.development.js:12502
performWorkOnRoot @ react-dom.development.js:12452
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
interactiveUpdates @ react-dom.development.js:12597
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
mapbox-gl.js:29 e {status: 404, url: "http://localhost:8080/data/wld_airports.mbtiles/{z}/{x}/{y}.pbf", name: "e", message: "Not Found"}`

Its weird since I actually am able to display these data on a local OL map.

**Comment by pathmapper** [comment]
Closing here - if this is still an issue, please let us know and we'll reopen the issue.

**Comment by elanioazul** [comment]
Hi,
I am having sort of the same problem:
I am able to display succesfully this group of geoserver layers in qgis with no problem, and through the Network activity panel in qgis I see all tiles served:
http://localhost:8080/geoserver/gwc/service/tms/1.0.0/burgos-callejero@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf

On the other hand, when adding it as a Vector (XYZ URL) in maputnik version Editor: 1.7.0; Desktop: 1.0.7, I don´t even get any signal of it in my browser network.

If I do http://localhost:8080/geoserver/gwc/service/tms/1.0.0/burgos-callejero@EPSG%3A900913@pbf/{x}/{-y}/{z}.pbf or http://localhost:8080/geoserver/gwc/service/tms/1.0.0/burgos-callejero@EPSG%3A900913@pbf/{x}/{y}/{z}.pbf nothing happens also.

What I migh be missing?
Thx

**Comment by jlpoolen** [comment]
Greetings,
I, too, am **having the same sort of problem.**

I logged an Issue #905 because I could not get Maputnik to see (or even make requests to) data served from a MapLibre Martin server on port 3000 in the form of ZXY.

`http://localhost:3000/jlptiles/{z}/{x}/{y}`
 The Martin server which I built was validated with QGIS. 

My Issue was converted into Discussion.

I launched my martin server and maputnik, both on a Debian server, and then tried accessing maputnik from my Window workstation using Firefox and 2 CORS errors appeared without my doing anything within the interface.  Here are the error messages copied form the Firefox console in full:

1. 03:12:41.617 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8888/styles. (Reason: CORS request did not succeed). Status code: (null).
2. 03:12:42.183 Failed to process sources for 'https://api.maptiler.com/tiles/v3-openmaptiles/tiles.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL' SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data App.tsx:671:11

![firefox_2024-06-19_03-15-26](https://github.com/maplibre/maputnik/assets/227313/069417e5-ebf8-40a7-a8e2-59e4ec3a6407)
