### ISSUE TITLE
Style Settings, Export Style, Sources: Apply changes

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#416]
Changes are only applied when closing the modal via the close button.

It is also possible to close the modal with a click beside the modal but then changes are discarded.

![image](https://user-images.githubusercontent.com/20856381/47085817-11886680-d218-11e8-8e64-aabf95998123.png)

This is confusing (it was at least to me :smile:).

It would be better to make the behavior consistent, so that a closing click beside the modal also applies the changes.

Another option would be to add a "save" button to apply changes and the close button only closes the modal (without applying the changes).

**Comment by orangemug** [comment]
Good find, I would bet quite a few people are really annoyed/confused by this bug.

**Comment by orangemug** [comment]
This bug is also present when pressing `ESC` to exit the modal. Although it's slightly different than described. The `<input/>`'s update the style when they lose focus (blur), so if I edit the style name in the 'settings modal' then press `ESC` no changes will be saved back to the style. However if I were to move focus to another field in the settings modal before pressing `ESC` then the changes would be saved.

I think we should fix the issue, without adding a 'Save' button. This is how the editing layer properties works at the moment, you edit the background color it updates the style, without any other interaction. Also note the current codebase makes a few assumptions that a blur events update the values.

So where do we go from here. I think what's going on here is that `react-aria-modal` uses [keydown](https://github.com/davidtheclark/react-aria-modal/blob/master/src/react-aria-modal.js#L41)/[mousedown](https://github.com/davidtheclark/react-aria-modal/blob/master/src/react-aria-modal.js#L130) events for `underlayClickExits`/`escapeExits` which means that the `blur` events on the `<input/>`'s don't trigger before the DOM is destroyed.

I _think_ `react-aria-modal` should ideally be using `keyup`/`mouseup`, but I'm assuming that would be a big breaking change for that lib, also there are probably good reasons (I'm unaware of) why they are not using these events.

All we need to do is delay the event until the next iteration of the event loop. There is a pull request for this <>
