### ISSUE TITLE
No HTTP version of https://maputnik.github.io/editor

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#420]
One person wrote in response to the survey that she is annoyed by the lack of an HTTP version of the online editor.

Do you think that such version makes sense?

Is it a big thing to make such a version?

I guess this version would have to function outside GitHub Pages.

**Comment by pathmapper** [comment]
It would be interesting to know why this person would like to have a `http://` version, I guess it is because of browser restrictions when dealing with sources not served over `https://`.

From https://github.com/maputnik/editor/issues/155#issuecomment-397797922:

> If we allow http:// we can't do auth because it would compromise security

**Comment by gregorywolanski** [comment]
It would be interesting to know, I agree, but I don’t have email address of this person. :/ :)

**Comment by pathmapper** [comment]
Maputnik desktop CLI binaries for Linux, OSX and Windows are available again which could be used for serving via `http`: 
https://github.com/maputnik/editor/wiki/Maputnik-CLI
https://github.com/maputnik/editor/releases/tag/v1.5.0

Closing here since a workaround is available and 

> HTTPS enforcement is required for GitHub Pages sites using a github.io domain that were created after June 15, 2016.

(from https://help.github.com/en/articles/securing-your-github-pages-site-with-https)

**Comment by pathmapper** [comment]
@orangemug, could you please change the link here to `https` (it redirects to `https`)?

![Auswahl_580](https://user-images.githubusercontent.com/20856381/60011979-31134100-967b-11e9-95bb-9344db856918.png)
