### ISSUE TITLE
Debug options

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#460]
The following debug options are currently available using a query parameter:

| Debug Option  | Query Parameter | Demo |
| :---  | :---  | :---  |
| Tile boundaries  | `show-tile-boundaries` | [**Link**](https://maputnik.github.io/editor/?show-tile-boundaries=true)  |
| Collision boxes  | `show-collision-boxes` | [**Link**](https://maputnik.github.io/editor/?show-collision-boxes=true)  |
| Overdraw inspector  | `show-overdraw-inspector` | [**Link**](https://74-139128409-gh.circle-artifacts.com/0/artifacts/build/index.html?show-overdraw-inspector=true)  |

Until there is a general debug panel available as outlined in https://github.com/maputnik/editor/issues/252#issue-294367056, how about making these options available via shortcuts and adding them to the existing shortcut menu?

![image](https://user-images.githubusercontent.com/20856381/47908597-d5970780-de8d-11e8-8120-0b95c30dac99.png)

A shortcut for openening a link to `https://www.openstreetmap.org/#map={ZOOM}/{LAT}/{LON}`
(https://github.com/maputnik/editor/issues/82) could be also added there.

Even if a debug paneI would exist, I think it would be good to have these options available via shortcut anyway.

**Comment by orangemug** [comment]
So my thoughts are that we should only add shortcuts for actions that have

 - obvious side effects in the UI
 - an easy way to reverse the action

So for instance it's quite easy to accidentally hit a shortcut key, you could be typing without having focus on an `<input/>` for example. The current shortcuts mostly open modals, which is fine because there is an obvious way out by pressing the `[x]` button

So if we do add the following as shortcuts we'd also need a way to reverse that in the UI

 - Tile boundaries
 - Collision boxes
 - Overdraw inspector

I feel like that means we'd need a UI to enable/disable these features as well as a visual cue for those that these are enabled.

Thoughts?

**Comment by pathmapper** [comment]
Good points.

What about a new _Debug_ modal which is available from the toolbar? This would be independent from shortcuts.

There could be buttons/check-boxes which are also indicating whether a debug option is on/off.

#82 could go in there too, like how https://enable-cors.org/ opens in a new tab from the _Open_ modal.

---

Regarding shortcuts for these:

Maybe use somthing like `CTRL` + `...` or `SHIFT` + `CTRL` + `...` to prevent an accidentally hit like how you described.

A shortcut could be used to toggle a debug option on/off (and also update the new _Debug_ modal), so the way out would be the same as the way in.



I'm also fine to have no shortcuts for these at all.

**Comment by pathmapper** [comment]
Or do you think it's better to do nothing here and wait for https://github.com/maputnik/editor/issues/252?

This would be also fine with me.
