### ISSUE TITLE
Mapbox source tiles not rendering

### ISSUE THREAD

**Issue by jonathanlevy** [maputnik/editor#462]
Fairly new to Maputnik but recently, I've noticed that I'm unable to render tiles when choosing Mapbox Sources (ie., mapbox://mapbox.mapbox-streets-v7).The map is empty at all zoom levels. Inspect Mode shows no layers either.  OpenMapTiles are working fine. I've tried across all browsers though I'm primarily working in Chrome. 

 I'm fairly certain this was working for me a few days ago but not anymore.  Am I doing something wrong or is this a bug? Thanks in advance for any help.

<img width="1130" alt="screen shot 2018-11-02 at 3 53 56 pm" src="https://user-images.githubusercontent.com/1958348/47944427-af3a9180-deb8-11e8-8c0a-46ad4982fd14.png">

**Comment by pathmapper** [comment]
Hi @jonathanlevy,

> I'm unable to render tiles when choosing Mapbox Sources


this is because we don't have currently a Mapbox access token available, this is tracked in #385.

With the current Maputnik online version you may use your own MB access token via "Style Settings".

Make sure to close the modal using the close button (cross (X) on the top right corner).

![auswahl_445](https://user-images.githubusercontent.com/20856381/47949745-911c7200-df48-11e8-9f44-047da4daeede.png)


It could be that you need to refresh the browser (F5) afterwards.

**Comment by jonathanlevy** [comment]
Thank you. Apologies for the duplicate, I didn't see that before. I think it was a matter of using the "x" to close for me.

**Comment by pathmapper** [comment]
No worries, thanks for your feedback!

> I think it was a matter of using the "x" to close

Yes, this behaviour is indeed confusing. There is already a fix for it (#416 / #418) which will included in the next release.
