### ISSUE TITLE
v1.6.0

### ISSUE THREAD

**Issue by orangemug** [maputnik/editor#473]
I've created a project for [v1.6.0](https://github.com/maputnik/editor/projects/2) for the remaining tickets that need doing, pre go live.

If anyone experiences any breaking changes that weren't in the v1.5.0 release, please raise a ticket.

**Comment by pathmapper** [comment]
Things to do:

- [ ] Merge https://github.com/maputnik/desktop/pull/5 after editor release and build CLI binaries.

**Comment by pathmapper** [comment]
Hey @orangemug,

we were asked by @klokan to start using the new Maptiler key (#542) as soon as possible. 

Do you have time to make a new release within a week and deploy it to https://maputnik.github.io/editor/? Otherwise we would run again into https://github.com/maputnik/editor/issues/541 (see https://github.com/maputnik/editor/issues/541#issuecomment-516066660).
 
We've done almost everything on our list https://github.com/maputnik/editor/projects/2 
(and a lot more :rocket:) and I think we could leave the remaining task for later.

I could build the Desktop CLI binaries after the editor release.

**Comment by orangemug** [comment]
@pathmapper sure, I'll build a beta release tomorrow for testing

**Comment by orangemug** [comment]
Release available for testing at <https://maputnik.github.io/releases/v1.6.0-beta/>

Pinging @pathmapper

**Comment by pathmapper** [comment]
Thanks @orangemug, looks good.

**Comment by orangemug** [comment]
Released https://maputnik.github.io/blog/2019/10/08/release-v1.6.0

**Comment by pathmapper** [comment]
Thanks @orangemug, would you mind updating also the release page: 
https://github.com/maputnik/editor/releases ?

**Comment by orangemug** [comment]
> Thanks @orangemug, would you mind updating also the release page:
https://github.com/maputnik/editor/releases ?

Done <https://github.com/maputnik/editor/releases>

**Comment by pathmapper** [comment]
Added desktop CLI binaries to the release: https://github.com/maputnik/editor/releases/tag/v1.6.0
