### ISSUE TITLE
A question about performance optimization

### ISSUE THREAD

**Issue by AllanHao** [maputnik/editor#534]
Hi, I designed a style with maputnik, it is smoother to browse in maputnik, but browsing with mapbox-gl.js will be a bit stuck, especially after level 13 in Beijing. 

So I want to ask if maputnik does a special optimization for loading? 

Demo: https://codepen.io/AllanHao/pen/Prmaoy

Looking forward to your answer.
BTW,my English is poor.

**Comment by pathmapper** [comment]
Hi @AllanHao,

good to hear that you like the performance of Maputnik, there are no special optimizations for loading. 

We are using currently Mapbox GL JS `v1.1.0-beta.1` in Maputnik `master` (your codepan sample uses `v1.0.0`).

According to the [changelog](https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.1.0-beta.1), `v1.1.0-beta.1` includes some performance updates, so I think it's worth to try out this beta version.

You may also check if the map window size is the same when you are using your style with Maputnik and "pure" MB GL JS because this could affect performance as well (more tiles/data which needs to be loaded and rendered).

Ref: https://github.com/maputnik/editor/issues/372

**Comment by AllanHao** [comment]
Thank you @pathmapper ,

After testing, I found that the loading speed is related to the font.

Starting with v0.54.0, mapbox-gl uses native fonts by default, which reduces the number of network requests, but slows the UI response. When I changed localIdeographFontFamily to false, the UI response speed will be faster.
