### ISSUE TITLE
Add Basemap AT style / source to the editor

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#554]
Just learned about the vector version of https://basemap.at/:
https://bergwerkgis.github.io/vtbasemapat/

Maybe we could add the style and/or source to the editor:
```
style.json : https://vtbasemapat.azurewebsites.net/json/style
tile.json : https://vtbasemapat.azurewebsites.net/json/tile
```

https://maputnik.github.io/editor/?style=https://vtbasemapat.azurewebsites.net/json/style#6.67/47.584/13.247

Thoughts?

cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
@pathmapper oh boy, I would love that.

Unfortunately I have to advise against it.

Neither the style nor the source are under my control.

Both originate from
https://www.data.gv.at/katalog/dataset/basemap-at-verwaltungsgrundkarte-vektor-osterreich
and have been created with ESRI tools and are not usable with open source tools (or any tools that adhere to the Mapbox specs) per se.

All my "proxy" does is some hard coded (🙈) mangling of the style.json and generating the tile.json on the fly and that might break as soon as there are any updates either to the original style or source.

Also, have you looked at the map?
https://bergwerkgis.github.io/vtbasemapat/map.html
It's super slow to load as some tiles are up to 4MB in size and the style has +800 layers.

If you ever feel cold during winter time, just open it and your CPU/GPU will take care of heating your apartment 😏 

The whole point behind my POC is to prove that ESRI styles and VT caches can be made available to other tools with minimal effort, despite some people claiming it's not possible.
Took about 10x times the effort to setup https://bergwerkgis.github.io/vtbasemapat/ compared to fixing the style and generating the correct tile.json.

**Comment by pathmapper** [comment]
@BergWerkGIS all right, no worries, thanks for the interesting background.

If the things are evolving in the direction of [OS Open Zoomstack](https://www.ordnancesurvey.co.uk/business-government/products/open-zoomstack), please let us know. :wink:

**Comment by BergWerkGIS** [comment]
Sorry for the kind of negative attitude of my previous comment, got carried away.

As I see it, the current state of basemap.at VT is far from being production ready and that might backfire if it gets added to Maputnik as a default option.
Some users might blame Maputnik for bad performance when the actual root cause lies in the tiles and the style.

**Comment by orangemug** [comment]
> Some users might blame Maputnik for bad performance...

I'll feel like that might also be us somewhat 😄, lucky our side of the performance issue will be getting fixed with https://github.com/maputnik/editor/pull/521

Also thanks from me for the background @BergWerkGIS super interesting. If you have the time and use Maputnik, please leave a comment over at #164
