### ISSUE TITLE
Better solution for tooltips

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#567]
From https://github.com/maputnik/editor/pull/563#issuecomment-542620356

> The Light position and Style Renderer tooltips are not fully visible and when scrolled down, the scroll position is set back to the initial position. This issue exists also for some tooltips of the Data Sources modal.

From https://github.com/maputnik/editor/pull/563#issuecomment-542644549

> If you collapse the JSON editor on a layer editing panel it's also an issue there as well. I think we should either find a good react tooltip library or alternatively a different UI for help text. I might be better to, on hover show a ? next to the label and then on click show link to the place in the mapbox-gl docs (or our own render of the mapbox-gl docs)

![tooltip_issue](https://user-images.githubusercontent.com/20856381/66907525-bf844780-f009-11e9-8d3d-7dbfff1c3849.gif)

**Comment by orangemug** [comment]
So I have an idea about this, how about we inline the documentation instead of a tooltip. As you hover over the label a `?` will appear that when clicked will display the documentation. Clicking it again will disable it.

<img width="352" alt="Screen Shot 2019-10-19 at 15 19 09" src="https://user-images.githubusercontent.com/235915/67146544-ffeefa00-f283-11e9-803b-41ef6bfc8279.png">

Demo: https://1609-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

Note: This is just a first pass and needs a lot more work, it's intended to get the discussion going on possible solutions for better inline documentation.

**Comment by pathmapper** [comment]
@orangemug in general I like this idea but I think it is too much "noise" that the `?` is appearing all the time if you hover over a field name or the corresponding value.

What about a mix of the current behaviour and your idea?
The mouse pointer changes to a question mark if hovered over a field where documentation is available (like it is currently) but instead of showing a tooltip on hover, on click the inline doc is shown like in your demo which could be closed using the X.

**Comment by pathmapper** [comment]
Hmm, the changing mouse pointer is also noise. I think I favour like it is in your demo, but the `?` appears only when hovering over field names, not the values.

**Comment by pathmapper** [comment]
From #425:

Regarding tooltips for `layout-line-line-cap` and `layout-line-line-join`

> The style spec has a text description of the different options:
> https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-line-line-cap
> https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-line-line-join
> 
> Maybe we could make this description with tooltips available.

Currently the tooltips of the [demo](https://1609-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html) are showing only the first sentence:
- The display of line endings.
- The display of lines when joining.
