### ISSUE TITLE
Feature request: metadata editor for layer

### ISSUE THREAD

**Issue by fredj** [maputnik/editor#578]
For one project, I need to add metadatas to every layers (the values are then used to build a layer tree). I'm currently editing the style in the editor and adding the metadatas with a text editor.

It would be very nice to be able to do that directly in the editor with something like the "Filter" editor: one button to add a metadata (key + value) and one button per entry to remove it.

**Comment by pathmapper** [comment]
Do you mean something like the existing `Comments` field, but with the ability to add a custom `key` and multiple `key`/`value` pairs?



![image](https://user-images.githubusercontent.com/20856381/67574022-ee04cf80-f739-11e9-8b66-423b03ca9b90.png)
![image](https://user-images.githubusercontent.com/20856381/67574403-a9c5ff00-f73a-11e9-92ab-e56ee9bd4437.png)


Results in:

```
{
      "id": "background",
      "type": "background",
      "metadata": {"maputnik:comment": "test"},
      "paint": {"background-color": "rgb(239,239,239)"}
}

```

**Comment by fredj** [comment]
> Do you mean something like the existing Comments field, but with the ability to add a custom key and multiple key/value pairs?

Yes, that exactly that.

BTW, the "Comments" help tooltip says that:
 _Comments for the current layer. This is non-standard and not in the spec._
which part is non-standard? the `maputnik:comment` or having metadata at layer level?

For what I understand from the spec, it's valid to have metadata at the layer level:
https://github.com/mapbox/mapbox-gl-js/blob/6453c38a5118e52e7cc7fb9b6e23d28e5bf5268b/src/style-spec/reference/v8.json#L562-L565

**Comment by pathmapper** [comment]
> Comments for the current layer. This is non-standard and not in the spec.

Yes, it's valid to have metadata at layer level. I think the tooltip refers to the fact that this is Maputnik specific metadata.

I think your feature request makes sense, it should be backwards compatible to `maputnik:comment`.

In the UI maybe replace `Comments` with `Metadata` where layer metadata will be listed and could be edited like you suggested:

> one button to add a metadata (key + value) and one button per entry to remove it

**Comment by orangemug** [comment]
The UI for metadata would itself just have to be a JSON editor I believe. This is because the `metadata` object could have nested objects. So for example if `metadata` was set to the following we couldn't list the values in the UI

```
{
  "metadata": {
    "foo": {
      "bar": 3 
    }
  }
}
```

The reason the _comment_ is kind of ok, although it's not fool proof, is that it has the `maputnik:` prefix. So although someone could set it to `metadata: {"maputnik:comment": {/* some object*/}}` the likely hood of the happening is quite slim. Whereas because another editor might want to store information in the metadata field in a nested manor I don't believe it's easy to make a nice UI.

Thoughts?

**Comment by pathmapper** [comment]
Didn't think of nested values, but you're right @orangemug that this could be the case.

I'm not sure if we would want another JSON editor for `metadata` because the existing JSON editor could be used for this task. Are there any other benefits beside that the `metadata` property could be added automatically if you start typing in the metadata editor?

**Comment by orangemug** [comment]
> I'm not sure if we would want another JSON editor for metadata because the existing JSON editor could be used for this task. Are there any other benefits beside that the metadata property could be added automatically if you start typing in the metadata editor?

Yeah I agree seems like it wouldn't add much value. Thoughts @fredj ?

**Comment by fredj** [comment]
Yes, I also agree that an other json editor is not the best solution. For me, editing the metadata in the existing editor will be fine.

After #562, the editor is now much more usable

**Comment by pathmapper** [comment]
Thanks @fredj, closing here.
