### ISSUE TITLE
Desktop: Style is reformatted and gl-style-format is not used

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#591]
When a style is exported with the online version, the style is formatted with [`gl-style-format`](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec#gl-style-format).

This is useful for unification of styles, especially when making PRs to style repositories, see https://github.com/openmaptiles/osm-bright-gl-style/issues/24.

When a style is modified with Maputnik Desktop, currently `gl-style-format` is not used and the style is reformatted somehow, see https://github.com/maputnik/osm-liberty/pull/66.

Maybe we could add `gl-style-format` to Desktop or at least make sure that an already with `gl-style-format` formatted style is not altered when edited with Desktop.

@lukaswelte any thoughts?

**Comment by kylebarron** [comment]
As a follow up, it looks like `format` is only invoked when the style is _exported_.
https://github.com/maputnik/editor/blob/3c93c41de1e1a38bba288c13a41afd1d213defbf/src/components/modals/ExportModal.jsx#L40

So when Maputnik desktop is used with
```
maputnik --watch --file style.json
```
any edits aren't formatted, since the style is auto updated on change, and the Export button is never used.

**Comment by pathmapper** [comment]
With Maputnik Desktop [v1.7.0](https://github.com/maputnik/editor/releases/tag/v1.7.0) the style is formatted properly (#606).
