### ISSUE TITLE
$type as key for old syntax filter cause switch to expressions syntax ui and opens export modal

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#712]
**Maputnik version**: v1.7.0, master
**Browser**: Firefox
**OS**: Linux

**Description of the bug**:

$type as key for old syntax filter cause switch to expressions syntax ui and opens export modal

**Steps to reproduce the behavior**:
1. Open the OSM Liberty style
2. Select layer `road_area_pattern`
3. Delete the existing filer using the trash can icon
4. Add a new filter and enter `$type` as key

**Style file or style URL**:
https://maputnik.github.io/editor?style=https://maputnik.github.io/osm-liberty/style.json

**GIF**:
![$type](https://user-images.githubusercontent.com/20856381/87221597-8517c300-c36d-11ea-99d4-052f907a1e32.gif)

**Comment by orangemug** [comment]
Good spot @pathmapper, it also happens if you type any of the shortcuts keys in the `id` field of the JSON editor. I assume it something about the react tree updating and not preventing the keyboard events from bubbling.

**Comment by orangemug** [comment]
I've found the issue. What's happening is we are trying to upgrade editor to the expression view because the validation fails, see 

https://github.com/maputnik/editor/blob/2cc179acc14b628d197471c7b79936ce1591adfe/src/components/FilterEditor.jsx#L157-L166

This method is flawed we need to find a way to check if the property array is trying to be an old-style filter and not an expression. I think we need to look at the `@mapbox/mapbox-gl-style-spec` see if it has anything

**Comment by pathmapper** [comment]
@orangemug what about `isExpressionFilter`?

https://github.com/mapbox/mapbox-gl-js/search?q=isExpressionFilter

**Comment by orangemug** [comment]
> ...what about `isExpressionFilter`?

That looks like the one we want 🎉
