### ISSUE TITLE
The 'index of' expression is not valid when using version 1.7

### ISSUE THREAD

**Issue by SakuraMS** [maputnik/editor#732]
error msg:Layer 'xxxx': Unknown expression "index-of". If you wanted a literal array, use ["literal", [...]].

**Comment by pathmapper** [comment]
Hi @SakuraMS, this is expected because Maputnik `v1.7.0` uses GL JS `v1.9.1` and the `index-of` expression was introduced with GL JS [`v1.10.0`](https://github.com/mapbox/mapbox-gl-js/blob/main/CHANGELOG.md#1100).

The `index-of` expression will be available in the upcoming  [`v1.8.0`](https://github.com/maputnik/editor/milestone/6) release or you could use Maputnik `master`.
