### ISSUE TITLE
CI failed for master 

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#734]
But the PR (https://github.com/maputnik/editor/pull/729) passed the tests. Looks like it's related to the selenium tests.

https://github.com/maputnik/editor/runs/1118988525?check_suite_focus=true

**Comment by orangemug** [comment]
So it looks like the following test is flakey, only passes sometimes...

```
[chrome 85.0.4183.83 linux #0-0]         groups
[chrome 85.0.4183.83 linux #0-0]            ✖ simple
```

I've re-run the tests and they passed the second time around. I'll leave this ticket open to take a look at that test see if I can work out what's wrong with it.

I'm also interested in trying out https://github.com/microsoft/playwright at some point as a replacement for webdriver, because webdriver has generally caused me a lot of pain over the years. I've spent much time battling webdriver, also there have been cases in the past because of flakey tests I've missed actual bugs in the code, saying to myself "oh that's a flakey test, I'll disable that for now, fix it later". I've also had to add a few work arounds for genuine bugs in chromedriver/webdriver to do with text entry.  

**Note:** The windows build is now failing, whereas it was the chrome build previously. I've seen this also on occasion also with the windows env on github actions, I think it might be an environment issue, although I'm not 100% about that.

**Comment by pathmapper** [comment]
@orangemug yeah, we had webdriver issues also here in the past.

https://github.com/microsoft/playwright looks interesting.

> I'll leave this ticket open to take a look at that test see if I can work out what's wrong with it.

Maybe the reason is one of these lines: 
https://github.com/maputnik/editor/blob/master/test/functional/layers/index.js#L485-L487

The test is about automatic grouping and I just did this test manually and the last added layer wasn't visible in the viewport after expanding the group (there was a need for me to scroll down to get it into the viewport).

![failing_test](https://user-images.githubusercontent.com/20856381/93706501-1ef6ab80-fb27-11ea-8831-b5f4b385d8fa.gif)

So we could try to scroll down the layer list after https://github.com/maputnik/editor/blob/master/test/functional/layers/index.js#L483. 





**Note**: I just manually rerun the workflow because the failing CI badge didn't look nice on https://github.com/maputnik/editor/

**Comment by pathmapper** [comment]
Or we need a little timeout after https://github.com/maputnik/editor/blob/master/test/functional/layers/index.js#L483 to be sure that the _animation_ expanding the group has finished.

**Comment by pathmapper** [comment]
No issue anymore after #778 :-)
