### ISSUE TITLE
how to interpolate colors accoding to data provided in mbtiles

### ISSUE THREAD

**Issue by briantran37** [maputnik/editor#741]
I am having trouble understanding how the data is pulled from this example to interpolate colors accordingly

https://docs.mapbox.com/mapbox-gl-js/example/updating-choropleth/

whenever i try , the colors of the vector mbtiles doesnt assign the colors accordingly but just stays one color. 

```
 {
  "id": "<sourceid>",
  "type": "fill",
  "source": "<source-data>",
  "source-layer": "<source-mbtiles>",
  "layout": {"visibility": "visible"},
  "maxzoom": 4,

  "paint": {
    "fill-color": [
      "interpolate",
      ["linear"],
      ["get", "<source-data>"],
      1,
      "#67B2E5",
      2,
      "#6E19B4",
      3,
      "#144BED",
      4,
      "#020096",
      6,
      "#C196E6",
      8,
      "#AE6EE6",
      12,
      "#9B50DC",
      18,
      "#8A32D7",
      24,
      "#6E19B4"
    ],
    "fill-antialias": true,
    "fill-opacity": 0.185,
    "fill-translate": [0, 0]
  }
}
```

![image](https://user-images.githubusercontent.com/72456221/98994819-69c8ea00-24fe-11eb-9d44-04dacfa5c3de.png)

**Comment by pathmapper** [comment]
Hi @briantran37,

sorry, but this is not really to debug since you didn't provide a live example which reproduces the issue.

Also this appears not to be a bug related to Maputnik, it seems to be a general question about the use of Mapbox GL JS.

Here are docs regarding the use of the interpolate expression: 
https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#interpolate

As stated in the issue template, we recommend to ask your question at https://gis.stackexchange.com/ and read https://gis.stackexchange.com/help/how-to-ask before you do so (please keep in mind that you're asking there in a general GIS forum, not a dedicated support channel).
