### ISSUE TITLE
Display more labels in small zoom levels

### ISSUE THREAD

**Issue by xyzlr2** [maputnik/editor#748]
Maputnik version: v1.7.0
Browser: Edge
OS: Windows

Despite of having minzoom set to 12, most of the residential labels appear not until Zoom Level 15 if I choose to set the symbol placement on line-center. In my configuration, there are no layers that should overlap or displace the residential labels. Also, the text should be short enough to displace in lower zoom levels. Is there a way to configure how many labels are drawn?

Zoom Level 15:
<img src="https://user-images.githubusercontent.com/78598262/107039750-94a1a200-67be-11eb-8957-d17695722c74.png" width="600">

Zoom Level 14:
<img src ="https://user-images.githubusercontent.com/78598262/107039798-a3885480-67be-11eb-98f8-7e2a9bc31d17.png" width="600">

**Comment by pathmapper** [comment]
@xyzlr2 it's impossible to diagnose this issue without knowing which style and data source you are using.

Some hints:

> Despite of having minzoom set to 12, most of the residential labels appear not until Zoom Level 15.

Are you sure your data source is containing the features used for labeling at lower zoom levels?

> Is there a way to configure how many labels are drawn?

Yep, many ways. I would start with trying to use `"text-allow-overlap": true`.

From our issue template:

> If you are having general Maputnik mapping questions, please asking them at https://gis.stackexchange.com/ using the 'maputnik' tag https://gis.stackexchange.com/questions/tagged/maputnik and read https://gis.stackexchange.com/help/how-to-ask before you do so (please keep in mind that you're asking there in a general GIS forum, not a dedicated support channel

So I'm going to close here because this is a general Maputnik mapping question and neither a bug report nor a feature request.

**Comment by zouyaoji** [comment]
@xyzlr2 Hello, I also encountered this problem. Is there a problem with the slicing scheme?
