### ISSUE TITLE
Question not an issue, Open source?

### ISSUE THREAD

**Issue by mylastore** [maputnik/editor#749]
All default styles presented on the editor are open source? I am a bit confused about why every map mentions MapBox rendered
We are planning to use OpenStreetMaps on our own server and just need to know if there is any legality with MapBox if we use the default styles use here. 

Hoe I make sense.

**Comment by ThomasG77** [comment]
Looking at https://github.com/maputnik/editor/blob/51fa4a4377a796106acbee5a815ada03b10ccceb/src/config/styles.json

All styles are based on OpenMapTiles schema (OpenSource spec about common vector tiles content to ease reuse for multiples styles https://openmaptiles.org/schema/). OpenMapTiles created to avoid legal issue(s) with Mapbox due to history from OSM2VectorsTiles e.g https://github.com/osm2vectortiles/osm2vectortiles/issues/387#issuecomment-273492760

Below styles are all based on OpenMapTiles schema

* OSM Liberty https://github.com/maputnik/osm-liberty
* Maptiler Basic https://github.com/openmaptiles/maptiler-basic-gl-style
* Dark Matter https://github.com/openmaptiles/dark-matter-gl-style
* Positron https://github.com/openmaptiles/positron-gl-style
* OSM Bright https://github.com/openmaptiles/osm-bright-gl-style
* Toner https://github.com/openmaptiles/maptiler-toner-gl-style

The other styles listed from first link are based on Zoomstack tiles, done by Ordnance Survey for UK area

**Comment by pathmapper** [comment]
Thanks @ThomasG77 for writing this up :+1: 

Here's a an Ordnance Survey style repo, but I currently don't know if it's up-to-date:
https://github.com/OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets/tree/master/Vector%20Tiles/Mapbox%20GL%20Styles

There's already a ticket tracking improvements for data sources and styles metadata: https://github.com/maputnik/editor/issues/643
