### ISSUE TITLE
Support for maplibre

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#781]
Since this topic was raised in https://github.com/maputnik/editor/issues/775, this issue is to discuss about support for maplibre: https://github.com/maplibre/maplibre-gl-js

- mapbox-gl version 1.x. -> backward compatible to mapbox-gl

- maplibre-gl version 2 -> non-backward compatible

**Comment by jsehner** [comment]
Please add Maplibre GL JS as Style renderer.
The library has a fast growing community.
Maputnik ist still the best open source editor, but without MapLibre losing benefit.

**Comment by lseelenbinder** [comment]
Hi @pathmapper, I'd like to take a look at this, if possible. Unfortunately, I'm not well-versed in the code, so I can't estimate how much effort it would be.

I'm eager to see support for recent MapLibre improvements (e.g., 3D) in the editor! I should be able to get a few people to assist from the MapLibre community, as well, if it turns out to be more involved than expected.

(cc @nyurik)

**Comment by lseelenbinder** [comment]
I've made decent progress locally, and will be pushing a _draft_ PR with working but not perfect code tomorrow. Looks like it'll be mostly a drop-in replacement!

**Comment by tordans** [comment]
Is this still right, now that #812 was merged?
https://github.com/maputnik/editor/blob/master/src/components/ModalSettings.jsx#L243-L246

<img width="398" alt="image" src="https://github.com/maputnik/editor/assets/111561/2d277bfd-b0ea-47bf-8c9b-7de8855086a2">

**Comment by tordans** [comment]
It looks like the docs are still referring to Mapbox GL JS in https://github.com/maputnik/editor#develop

**Comment by nyurik** [comment]
@tordans definitly needs fixing, PRs welcome :)

**Comment by kevinschaul** [comment]
Good point @tordans. I'll open an issue.
