### ISSUE TITLE
inconsistent label offsets

### ISSUE THREAD

**Issue by jonahadkins** [maputnik/editor#98]
using `maputnik_darwin 1.01` in a chrome browser - i'm experiencing some inconsistent label offsets - setting 3.5 (pictured below) different distances depending on the point ...sorry if this has been addressed or brought up already .
![screen shot 2017-02-08 at 8 11 36 pm](https://cloud.githubusercontent.com/assets/5178200/22764862/39b116c4-ee3b-11e6-881f-5ca471485c83.png)

**Comment by lukasmartinelli** [comment]
I guess this is normal Mapbox GL behavior.
Not sure if it is in the spec for the offset field.

On Feb 9, 2017 8:18 AM, "Jonah Adkins" <notifications@github.com> wrote:

using maputnik_darwin 1.01 in a chrome browser - i'm experiencing some
inconsistent label offsets - setting 3.5 (pictured below) different
distances depending on the point ...sorry if this has been addressed or
brought up already .
[image: screen shot 2017-02-08 at 8 11 36 pm]
<https://cloud.githubusercontent.com/assets/5178200/22764862/39b116c4-ee3b-11e6-881f-5ca471485c83.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/maputnik/editor/issues/98>, or mute the thread

**Comment by jonahadkins** [comment]
ah, you are correct - it appears i had `text-anchor` set to `center` - changing that to `left` produced the desired results.  

thank you v. much! 👍 👏 💯
